name: first-action
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: first job
              run: echo "first job"
            - name: check out
              uses: actions/checkout@v3
            - name: list files
              run: ls
            - name: read file
              run: cat README.md